Add troubleshooting tips on Crossplane package handling
crossplane/crossplane pull request #2463
Opened 2021-08-09 15:01 UTC by morningspace

### Description of your changes

This PR is about to add some troubleshooting tips on the handling of Crossplane package which can be complements to the official Crossplane documents on the use of Crossplane package. It covers:

* Handling Crossplane Package Dependency
* Installing Crossplane Package

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

This is documentation change. No code involved.

[contribution process]: https://git.io/fj2m9

2021-08-09 15:04 UTC, hasheddan reviewed
@morningspace thanks so much for adding this! Could you add [sign-off](https://cert-manager.io/docs/contributing/sign-off/) to your commit? :)

2021-08-09 16:32 UTC, hasheddan requested changes

2021-08-09 16:32 UTC, hasheddan commented on docs/reference/troubleshoot.md
> +Please make sure you provide the fully qualified address to the dependent package, but do
I think the "parent" package here is technically the dependent package :) 
```suggestion
Please make sure you provide the fully qualified address to the dependency package, but do
```

2021-08-09 16:32 UTC, hasheddan commented on docs/reference/troubleshoot.md
> +it may not be able to find the appropriate version for the dependent package even it says
```suggestion
it may not be able to find the appropriate version for the dependency package even it says
```

2021-08-09 16:32 UTC, hasheddan commented on docs/reference/troubleshoot.md
> +Below is an example where a configuration package depends on a provider pulled from `crossplane/provider-aws`.
can you make sure to capitalize Configuration and Package wherever talking about the package itself, and use `Configuration` and `Package` when talking about the actual k8s resources (which I believe you already do)
```suggestion
Below is an example where a Configuration package depends on a provider pulled from `crossplane/provider-aws`.
```

2021-08-09 16:32 UTC, hasheddan commented on docs/reference/troubleshoot.md
> +To inspect a particular package for troubleshooting, you can run `kubectl describe` against the corresponding resources,
Looks like some of the lines in this PR are not wrapped at 80 chars, could you update to match the rest of the doc? :)

2021-08-10 08:32 UTC, morningspace commented
Thanks @hasheddan for your comments. I've updated the contents according to your review comments. Let me know if there is anything else needs to be addressed.

2021-08-11 12:55 UTC, hasheddan approved these changes
@morningspace thank you again for your work on this! I'm sure this will serve as a useful resource for folks :)

2021-08-11 12:55 UTC, merged