Postpone the deletion of XRs and XRCs until their direct children are gone
crossplane/crossplane pull request #3320
Opened 2022-09-14 16:38 UTC by MisterMX

### Description of your changes

Add a check before `RemoveFinalizer` for both XR and XRC to postpone their deletion while their children are still alive.

Essentially
* postpone the deletion of an XRC while the referenced XR is still alive
* postpone the deletion of an XR while at least one composed resource is still live

Relates to #3225 (not sure if it fixes it, though)

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Manually and unit tests

[contribution process]: https://git.io/fj2m9

2022-09-14 17:08 UTC, bobh66 reviewed
I have a set of changes for 3225 in progress in both crossplane and crossplane-runtime  - I'd like to defer this change until those changes are in place as they are closely related to that work which is already being tested.

2022-09-14 21:37 UTC, bobh66 commented
I'm also concerned that this is a significant change in behavior to introduce without any controls attached to it.  I agree that it's a desirable behavior, but it has the potential to cause disruption in the way people are used to having things work, and I think it would be better to have it under the control of something like the compositeDeletePolicy: Foreground option that is in https://github.com/crossplane/crossplane/pull/3321

2022-09-15 07:24 UTC, MisterMX commented
> I agree that it's a desirable behavior, but it has the potential to cause disruption in the way people are used to having things work

@bobh66 do you have some potential disruption in mind? 

From my perspective it makes absolute sense to keep the XR and XRC around to allow the user to track potential deletion errors. You cannot do that if the object is gone instantly.

> I'm also concerned that this is a significant change in behavior to introduce without any controls attached to it.

This actually does not change the behaviour of the deletion process. Unlike the `Orphan` deletion policy where external resource are kept alive, the child resources are deleted in the same way as before.

It only takes longer until the XR object is actually deleted.

2022-09-15 13:51 UTC, bobh66 commented
> From my perspective it makes absolute sense to keep the XR and XRC around to allow the user to track potential deletion errors. You cannot do that if the object is gone instantly.

That's what foreground cascading deletion is for.  It delays the delete of the resources pointed at by ownerReferences until all dependencies have been deleted.

> This actually does not change the behaviour of the deletion process. Unlike the Orphan deletion policy where external resource are kept alive, the child resources are deleted in the same way as before.
> It only takes longer until the XR object is actually deleted.

Yes, it does.  The changes to the claim reconciler effectively force ALL kubectl delete commands of Claim objects to function as if the user has provided the --cascade=foreground command line option, instead of leaving the default "background" value.  There would be NO WAY to execute background deletion on a Claim object even if the user wants to.

I don't believe that choice should be forced upon the user by the claim reconciler - it should be controllable by the user either in the command line option (which doesn't work for Claims because they are namespaced and Composites are not) or the compositeDeletePolicy.

#3225 is not intended to change any existing behavior - it is intended to allow the user to specify that they WANT foreground cascading deletion and to allow Crossplane to functionally implement that deletion process using standard kubernetes processing.

I am willing to extend the changes for #3225 to include this functionality - I think it makes sense from a user experience point of view, but it would still need to be controlled by the compositeDeletePolicy=Foreground option so that it is not changing the default background propagation policy.

2022-09-15 21:33 UTC, negz commented on internal/controller/apiextensions/claim/reconciler.go
> +			log.Debug("Postponed deletion of claim because composite resource claim is still alive")
```suggestion
			log.Debug("Postponed deletion of claim because composite resource is still alive")
```

2022-09-15 21:33 UTC, negz commented on internal/controller/apiextensions/composite/api.go
> +		err := c.client.Get(ctx, nn, &obj)
Does this work? 🤔 How does the client know what GVK to get? I think you might need to set them on `obj`.

2022-09-28 22:04 UTC, negz requested changes
After a little more reading and thinking, I tend to agree with @bobh66 here. This PR is "manually" doing the same thing that foreground cascading deletion should do for us.

2022-09-30 20:58 UTC, closed without merging