Revamp 4-part composition series and use new Hugo capabilities
crossplane/crossplane pull request #3539
Opened 2022-12-19 15:41 UTC by cwilhit

This is a second submission attempt of my first PR, #3534. Reworked the tutorial to span 4-parts, but only show the first page in the TOC. Used conventions as recommended by Crossplane contributor docs around links and images.

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

2022-12-19 15:41 UTC, cwilhit commented
@plumbis PTAL

2022-12-28 16:00 UTC, plumbis requested changes
A few suggestions and a lot of little nits. 95% of the comments are about removing smart quotes/smart apostrophes.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +toc: true
you can remove `toc: true`, it's not used in the docs anymore.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +> Tip: Generally speaking, If you cannot find the provider you are looking for in the Upbound marketplace, the next step you must evaluate is whether to build the provider yourself (or consult a vend
Use one of the hint callout styles here. https://docs.crossplane.io/v1.10/contributing/docs/#hints-and-alert-boxes

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +# Build your XRD
Instead of a top level header `#` make this the `title:` value in the front matter.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +* The `group` is the declaration of where this API will live (in the future you could define multiple APIs and have them all be a member of the ‘compute.acme.co’ group).
Optional: you may want to consider using the new `hover highlight` docs feature. It's designed for exactly this use case of calling out lines of larger outputs. 

https://docs.crossplane.io/master/contributing/docs/#syntax-highlighting

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +# Build your Composition
Same as the build-xrd.md file, move this to the `title` front matter instead of a top-level header (`#`)

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +* The ‘spec.forProvider’ section is where you pass values for the required fields of the Managed Resource. This is also where you could set additional optional fields exposed by the Managed Resource.
your `spec.forProvider` ticks aren't code ticks

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +...
extra triple ticks

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +...
extra triple ticks

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +...
extra triple ticks

2022-12-28 16:00 UTC, plumbis commented on docs/guides/test-and-deploy.md
> +>Important: The last thing to do is configure provider-gcp with credentials. Those instructions can be found in the [Getting Started]({{<ref "master/getting-started/install-configure.md" >}}) guide
Use one of the hint callout styles here. https://docs.crossplane.io/v1.10/contributing/docs/#hints-and-alert-boxes

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +This is the third part of a four part tutorial to build an API for provisioning pre-configured VMs on top of the GCP Compute Engine service. If you have not already, you need to first [Build your XRD
use contractions when possible. "haven't" instead of "have not".

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +Similar to the XRD, it is useful to bootstrap the file by copying in from a “known good” `composition.yaml` and pruning it back to the basics. Using the same repo as before, copy the PostgreSQL [inst
Use "it's" instead of "it is".

"known good" and "XRDs" are using smart quotes instead of standard quotes.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +* It’s also convention to attach a label of whichever provider this API is built on top of (yours is GCP). This label can be used in `compositionSelector` in an XR or Claim.
"It's" isn't using a standard straight apostrophe. (`'`)

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +* Each Composition must declare that it is compatible with a particular type of Composite Resource using its `compositeTypeRef` field. The referenced version must be marked `referenceable` in the XRD
Use "it's" instead of "it is"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +This brings you to the main section of the composition, which is where you define the resources that will get composed by the composition and how the fields map (i.e. patch) between the composition a
Don't use `i.e.`, say something like "...how the fields map (or patch) between.."

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +* The apiVersion and kind of the resource comes straight from what is shown in the Upbound marketplace for that CRD.
Use "what's" instead of "what is"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +* The fields exposed to the end user are string enums, and the values do not directly map to the values needed by the Managed Resource, so we set up a transform to mutate the value inputted by users
"don't" instead of "do not"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-composition.md
> +Therefore, you need two add two additional composed Managed Resources to this Composition: a `Network` MR and a `Subnetwork` MR. Just as you did for the `Instance` MR, you can look these up on the Ma
Don't use `etc.`. You can just remove it from this sentence.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +This is the second part of a four part tutorial to build an API for provisioning pre-configured VMs on top of the GCP Compute Engine service. If you have not already, it is recommended to read [Plan
"haven't" instead of "have not"
"it's" instead of "it is"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +The previous part of the tutorial gave you a sense for the Managed Resources you need to compose for your API. It’s time to start authoring the Crossplane Composition (your API definition). Make a fo
`Composition's` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +You’ll start by authoring the `definition.yaml` file (which will define your XRD). Open it in your favorite code editor. At this current time, the Crossplane authoring experience unfortunately involv
"It's" instead of "It is"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +Click into the `platform-ref-gcp` Configuration  and click the link on the next page under “Source Code” to go to the source repo.
extra space between "Configuration" and "and"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +Click into the `platform-ref-gcp` Configuration  and click the link on the next page under “Source Code” to go to the source repo.
Smart quotes around `"Source Code"`

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +Within this GitHub repo, you are going to copy an existing XRD’s definition. You are going to use the PostgreSQL instance XRD and repurpose it for your needs. Copy the contents of the Postgre SQL [XR
`XRD's` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +An aside: these Configurations in the Marketplace are reference implementations. In some cases, you may want to build an API for which there is already an implementation (like a Kubernetes cluster or
"It's" instead of "it is"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +An aside: these Configurations in the Marketplace are reference implementations. In some cases, you may want to build an API for which there is already an implementation (like a Kubernetes cluster or
`doesn't` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +An aside: these Configurations in the Marketplace are reference implementations. In some cases, you may want to build an API for which there is already an implementation (like a Kubernetes cluster or
"we've" instead of "we have"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +Next, prune out all the fields that are irrelevant for your use case (i.e. they are specific to PostgreSQL) and you will end up with this. This is boilerplate.yaml that nearly all XRDs will want to h
Don't use `i.e.`. here you can write out "for example"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +* The `claimNames` field of the spec is where we define the claim that our XR offers. If you don’t want a publicly callable API, omit having a claimName. You want app teams to issue claims to “call”
`"call"` is in smart quotes.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +* The `group` is the declaration of where this API will live (in the future you could define multiple APIs and have them all be a member of the ‘compute.acme.co’ group).
`compute.acme.co` is in smart quotes. I don't know if you're quoting or using code ticks.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/build-xrd.md
> +* The `names` field of the spec is where we define the name of the XRD. Crossplane convention says we prefix the XRD name with an ‘X’.
`X` is in smart quotes.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +* Other app teams don’t want to hassle with knowing which properties to set or what sizes are outside of company policy–they just need a VM to host their app. We’ll only ask the app team to specify w
`don't` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +* Other app teams don’t want to hassle with knowing which properties to set or what sizes are outside of company policy–they just need a VM to host their app. We’ll only ask the app team to specify w
`‘small’, ‘medium’, or ‘large’` are in smart quotes.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +* Other app teams don’t want to hassle with knowing which properties to set or what sizes are outside of company policy–they just need a VM to host their app. We’ll only ask the app team to specify w
`policy–they` uses an EnDash. Use a standard hyphen or Emdash.
https://developers.google.com/style/dashes

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +From these requirements, you know you are going to be building an API abstraction on top of GCP’s Compute Engine service.
`GCP's` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +> Tip: Generally speaking, If you cannot find the provider you are looking for in the Upbound marketplace, the next step you must evaluate is whether to build the provider yourself (or consult a vend
Remove "Generally speaking" to sound more authoritative.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +> Tip: Generally speaking, If you cannot find the provider you are looking for in the Upbound marketplace, the next step you must evaluate is whether to build the provider yourself (or consult a vend
Use "can't" instead of "cannot"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +Now that you’ve found the right provider, next you should confirm it contains the API types (CRDs) that you need. Since the objective is to build a platform on Compute Engine VMs, use the search bar
`you've` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +Next, you should familiarize yourself with the API documentation of the CRD, especially the `spec` field. Make a note of the required objects under the `forProvider` field–as you build your API abstr
`field-as` uses an EnDash. Use a standard hyphen or Emdash.
https://developers.google.com/style/dashes

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +You can read the description provided by the CRD and see that, “Instance is the Schema for the Instances API. Manages a VM instance resource within GCE.” We’ve confirmed the correct CRD exists in the
Don't use smart quotes around "Instance is...within GCE."

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +It’s at this point you should be considering:
`It's` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +If the required fields are an `object` type, you can recursively expand the object’s fields and see what are the required fields for that nested object.
`object's` isn't using a standard apostrophe.

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +One last thing to look at during this planning phase is the “Examples” tab, which gives working samples of .yaml that could be passed to created instances of this CRD as a Managed Resource (which is
"Examples" is in smart quotes

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +One last thing to look at during this planning phase is the “Examples” tab, which gives working samples of .yaml that could be passed to created instances of this CRD as a Managed Resource (which is
"isn't" instead of "is not"

2022-12-28 16:00 UTC, plumbis commented on docs/guides/plan-api.md
> +One last thing to look at during this planning phase is the “Examples” tab, which gives working samples of .yaml that could be passed to created instances of this CRD as a Managed Resource (which is
`tutorial-which` uses an EnDash. Use a standard hyphen or Emdash.
https://developers.google.com/style/dashes

2022-12-28 16:00 UTC, plumbis commented on docs/guides/test-and-deploy.md
> +Confirm the package installed by confirming it’s `healthy` status shows `true`. You can also see it pulled in the provider-gcp dependency automatically by confirming its existence:
`it's` isn't using a standard apostrophe.

2023-01-11 21:34 UTC, negz commented
@cwilhit @plumbis should this PR be reopened against the new crossplane/docs repo?

2023-01-26 18:39 UTC, negz commented
I haven't heard back, so I'm going to close this. I'm pretty sure this would belong in the new docs repo.

2023-01-26 18:39 UTC, closed without merging