Increase delay before closing stale issues to 40 days
crossplane/crossplane pull request #4020
Opened 2023-04-26 19:26 UTC by gberche-orange

The 7 days current limit is preventing people away from keyboard to comment the issue and there is supported bot action to reopen them afterwards

See related side effect of misconfigured stale bot at https://github.com/actions/stale/issues/719

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2023-04-26 21:05 UTC, negz commented
@gberche-orange Can we compromise at 14 days please? 40 seems too long to me, in addition to the 90 days we wait before even marking an issue stale.

2023-04-27 07:09 UTC, gberche-orange commented
@negz 

>  Can we compromise at 14 days please? 40 seems too long to me, in addition to the 90 days we wait before even marking an issue stale.

The problematic aspect for the community is missing `days-before-close` window requiring to comment with a /fresh comment. Being away from keyboards for 14 days is still pretty frequent for many professionals (being xmas breaks, summer holidays or sick leaves)

What about reducing `days-before-stale` from 90 to 70 days, and increase  `days-before-close` from 7 to 30 days ?

2023-04-27 09:36 UTC, jbw976 commented
I appreciate your concern here @gberche-orange and taking the initiative to update the process.  I agree with @negz though that 14 days before close is a reasonable compromise - I wouldn't reduce the `days-before-stale` down from 90 because that will just increase the frequency that we get stale markings that need intervention.

14 days is reasonable since I don't think we need to optimize here to fully cover the maximum durations of people's vacations - if someone takes extended time off and misses saving an issue from being closed, they are still more than welcome to request it to be re-opened by adding a comment with their reasoning.  The issue isn't closed forever 😉 

Additionally, members of the Crossplane org should have permissions to re-open issues themselves.  Anyone is welcome to join the org as a member by following the defined process in https://github.com/crossplane/org/blob/main/processes/new-member.md 🙌

2023-04-27 16:45 UTC, gberche-orange commented
Thanks, the PR is updated with `days-before-close` to 14 days.

> > Anyone is welcome to join the org as a member by following the defined process in https://github.com/crossplane/org/blob/main/processes/new-member.md 🙌

> For new members to be added to the Crossplane Org, the candidate must open an issue using the the [New Member template](https://github.com/crossplane/org/blob/main/.github/ISSUE_TEMPLATE/new-member.md) after they have spoken to two current Org members who have agreed to sponsor their membership request.

@jbw976  @negz Would you sponsor my request to join the community ? Here are the [list of issues](https://github.com/search?q=org%3Acrossplane+author:gberche-orange&type=issues) I have previously contributed.

2023-04-29 21:54 UTC, negz commented
> Thanks, the PR is updated with days-before-close to 14 days.

Thank you.

> @jbw976 @negz Would you sponsor my request to join the community ? Here are the [list of issues](https://github.com/search?q=org%3Acrossplane+author:gberche-orange&type=issues) I have previously contributed.

Of course!

2023-04-29 21:56 UTC, negz requested changes
@gberche-orange I just noticed that we mention the days-before-close in the stale issue and stale PR messages. Could you update those to mention 14 days rather than 7 please.

2023-05-02 07:29 UTC, gberche-orange commented
> I just noticed that we mention the days-before-close in the stale issue and stale PR messages. Could you update those to mention 14 days rather than 7 please.

Thanks for catching this. Fixed in 435643a

2023-05-02 20:32 UTC, negz approved these changes

2023-05-04 00:41 UTC, merged

2023-05-08 16:53 UTC, jbw976 commented
> @jbw976 @negz Would you sponsor my request to join the community ? Here are the [list of issues](https://github.com/search?q=org%3Acrossplane+author:gberche-orange&type=issues) I have previously contributed.

yes definitely @gberche-orange! feel free to open an issue now following the process: https://github.com/crossplane/org/blob/main/processes/new-member.md 💪