Add PITS Global Data Recovery Services to the list of adopters
crossplane/crossplane pull request #4096
Opened 2023-05-23 15:29 UTC by pheianox

This pull request adds new entry in the adopters list

2023-05-24 23:05 UTC, negz approved these changes

2023-05-25 12:07 UTC, jbw976 requested changes
Awesome, thank you for sharing your usage of Crossplane with the rest of the community, we definitely appreciate hearing about this! 💪 

Just 1 blocking comment to address here, thank you!

2023-05-25 16:32 UTC, jbw976 approved these changes

2023-05-25 17:05 UTC, merged

2023-05-25 17:40 UTC, pheianox commented
@jbw976 Thank you too, my friend!