composite: add fuzzer
crossplane/crossplane pull request #4198
Opened 2023-06-19 12:30 UTC by AdamKorcz

### Description of your changes

Adds a fuzzer for the composite controller. It calls `FunctionIOObserved`, `FunctionIODesired`, `UpdateResourceRefs `in the same order as the controller does to mimic real-world data flow.

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

`go test -fuzz=FuzzPTFComposer`

[contribution process]: https://git.io/fj2m9

2023-06-20 01:06 UTC, negz approved these changes
One nit, but otherwise LGTM. Thanks!

2023-06-20 01:06 UTC, negz commented on internal/controller/apiextensions/composite/fuzz_test.go
> +	"github.com/ghodss/yaml"
Nit: We typically try to use https://pkg.go.dev/sigs.k8s.io/yaml instead. Pretty sure it's the same API.

2023-06-20 01:09 UTC, negz requested changes
Whoops, just noticed a bunch of CI is failing. Please go through the PR checklist - it should help you resolve this.

2023-06-29 14:33 UTC, AdamKorcz commented
@negz Should be ready.

2023-06-29 14:43 UTC, phisco approved these changes

2023-07-24 07:46 UTC, merged